### PR TITLE
ci: run with node20

### PR DESCRIPTION
**Pull request by idanran**

### CODE REVIEW

**Comment by ilharp** [comment]
四个文件为啥只改一个

**Comment by idanran** [comment]
> 四个文件为啥只改一个

改好了

**Comment by idanran** [comment]
另外问下，为啥 [downgrade node to v20.3.1](https://github.com/koishijs/koishi-desktop/commit/a3667f4c80eb4eeb398c7f793c31c61a02fb90d0)

**Comment by ilharp** [comment]
> 另外问下，为啥 [downgrade node to v20.3.1](https://github.com/koishijs/koishi-desktop/commit/a3667f4c80eb4eeb398c7f793c31c61a02fb90d0)

https://github.com/nodejs/node/issues/48673

**Review by ilharp — APPROVED** [review]

**Comment by idanran** [comment]
> [nodejs/node#48673](https://github.com/nodejs/node/issues/48673)

原来如此

**Pull request merged**
